{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "wildlife-explorer.fullname" . }}-secret-store
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "wildlife-explorer.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "wildlife-explorer.serviceAccountName" . }}
{{- end }}
