import React,{useMemo,useState} from 'react';import{Search,MapPin,Leaf,ShieldCheck,ArrowRight,X}from'lucide-react';import{animals,habitats}from'./data/animals';import'./styles.css';
function App(){const[q,setQ]=useState('');const[selected,setSelected]=useState(null);const filtered=useMemo(()=>animals.filter(a=>(a.name+a.region+a.habitat).toLowerCase().includes(q.toLowerCase())),[q]);return <>
<nav><div className="brand">WILD<span>ATLAS</span></div><div className="navlinks"><a href="#species">Species</a><a href="#habitats">Habitats</a><a href="#conservation">Conservation</a></div><a className="navbtn" href="#species">Explore wildlife</a></nav>
<header className="hero"><div className="heroShade"></div><div className="heroContent"><p className="eyebrow">THE LIVING PLANET • FIELD GUIDE</p><h1>Discover the wild.<br/><em>Protect its future.</em></h1><p className="lead">Journey from African savannas to Arctic sea ice and meet the remarkable animals that make Earth extraordinary.</p><a className="cta" href="#species">Explore the atlas <ArrowRight size={18}/></a></div><div className="stats"><div><b>12</b><span>Featured species</span></div><div><b>4</b><span>Major habitats</span></div><div><b>1</b><span>Shared planet</span></div></div></header>
<section className="intro"><p className="eyebrow dark">A WORLD WORTH KNOWING</p><h2>Every species tells a story.</h2><p>Wildlife reflects millions of years of adaptation. Explore how animals survive, interact with their ecosystems and face a rapidly changing world.</p></section>
<section id="species" className="species"><div className="sectionHead"><div><p className="eyebrow dark">SPECIES DIRECTORY</p><h2>Meet the remarkable</h2></div><div className="search"><Search size={18}/><input aria-label="Search wildlife" placeholder="Search species, habitat, region…" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="grid">{filtered.map(a=><article className="card" key={a.id} onClick={()=>setSelected(a)}><div className="photo"><img src={a.image} alt={a.name}/><span className="status">{a.status}</span></div><div className="cardBody"><p className="latin">{a.scientific}</p><h3>{a.name}</h3><div className="meta"><span><MapPin size={14}/>{a.region}</span><span><Leaf size={14}/>{a.habitat}</span></div><p>{a.description.slice(0,145)}…</p><button>View species profile <ArrowRight size={15}/></button></div></article>)}</div>{filtered.length===0&&<p className="empty">No species match that search.</p>}</section>
<section id="habitats" className="habitats"><div className="sectionHead light"><div><p className="eyebrow">ECOSYSTEMS</p><h2>Explore their worlds</h2></div><p>Habitats are more than scenery. They are complex systems connecting climate, plants, predators, prey and people.</p></div><div className="habitatGrid">{habitats.map(h=><div className="habitat" key={h.name} style={{backgroundImage:`linear-gradient(0deg,rgba(5,18,13,.85),rgba(5,18,13,.05)),url(${h.image})`}}><div><h3>{h.name}</h3><p>{h.desc}</p></div></div>)}</div></section>
<section id="conservation" className="conservation"><div className="conText"><p className="eyebrow dark">CONSERVATION</p><h2>Knowledge becomes stewardship.</h2><p>Healthy wildlife populations depend on connected habitat, functioning ecosystems and communities equipped to coexist with nature. Conservation combines science, protected areas, responsible policy, local leadership and long-term monitoring.</p><div className="pillrow"><span><ShieldCheck/>Protect habitat</span><span><Leaf/>Restore ecosystems</span></div></div><div className="quote"><span>“</span><p>The future of wildlife is inseparable from the future of the landscapes and communities around it.</p></div></section>
<footer><div className="brand">WILD<span>ATLAS</span></div><p>An educational wildlife exploration experience.</p><small>Built for learning, curiosity and conservation awareness.</small></footer>
{selected&&<div className="modalBackdrop" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><img src={selected.image} alt={selected.name}/><div className="modalBody"><p className="latin">{selected.scientific}</p><h2>{selected.name}</h2><div className="facts"><span><b>Region</b>{selected.region}</span><span><b>Habitat</b>{selected.habitat}</span><span><b>Diet</b>{selected.diet}</span><span><b>Lifespan</b>{selected.lifespan}</span><span><b>Weight</b>{selected.weight}</span><span><b>Status</b>{selected.status}</span></div><p>{selected.description}</p><h4>Remarkable facts</h4><ul>{selected.facts.map(f=><li key={f}>{f}</li>)}</ul></div></div></div>}</>};export default App;
