replicaCount: 2

image:
  repository: 068704208379.dkr.ecr.us-east-1.amazonaws.com/wildlife-app
  pullPolicy: IfNotPresent
  tag: "v1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

namespace:
  create: true
  name: wildlife-explorer

loadBalancer:
  enabled: true
  port: 4173
  annotations: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: "gp2"
